#ifndef RBUFLOGD_PUB_COMMON_TYPES_H
#define RBUFLOGD_PUB_COMMON_TYPES_H

#define RBUF_PROD_ID_MAX_LEN    8

typedef enum {
  RBUF_LOG_LEVEL_DEBUG, 
  RBUF_LOG_LEVEL_INFO,
  RBUF_LOG_LEVEL_WARNING,
  RBUF_LOG_LEVEL_ERROR,
} rbuflogd_log_level_t;

#endif /* RBUFLOGD_PUB_COMMON_TYPES_H */
